

extern ssize_t ukl_write(int fd, const void* buf, size_t count) ;
extern ssize_t ukl_read(int fd, const void* buf, size_t count);
extern long ukl_open(const char* filename, int flags, unsigned short mode);
extern long ukl_openat(int dfd, const char * filename, int flags, umode_t mode);
extern long ukl_close(int fd);
extern void ukl_exit_group(int error_code);
extern int ukl_socket(int family, int type, int protocol);
extern int ukl_bind(int fd, struct sockaddr  *umyaddr, int addrlen);
extern int ukl_connect(int fd, struct sockaddr  *uservaddr, int addrlen);
extern int ukl_listen(int fd, int backlog);
extern int ukl_accept(int fd, struct sockaddr *upeer_sockaddr, int *upeer_addrlen);
extern int ukl_accept4(int fd, struct sockaddr *upeer_sockaddr, int *upeer_addrlen, int flags);
extern int ukl_ioctl(int fd, int cmd, long arg);
extern int ukl_recvfrom(int fd, void  *ubuf, size_t size, unsigned int flags, struct sockaddr  *addr, int  *addr_len);
extern int ukl_sendto(int fd, void *buff, size_t len, unsigned int flags, struct sockaddr *addr, int addr_len);
extern long ukl_recvmsg(int fd, struct user_msghdr *msg, unsigned int flags);
extern int ukl_recv(int fd, void  *ubuf, size_t size, unsigned int flags);
extern int ukl_send(int fd, void *buff, size_t len, unsigned int flags);
extern int ukl_setsockopt(int fd, int level, int optname, char *optval, int optlen);
extern int ukl_getsockopt(int fd, int level, int optname, char *optval, int * optlen);
extern int ukl_getsockname(int fd, struct sockaddr *usockaddr, int *usockaddr_len);
extern long ukl_arch_prctl(int option, unsigned long arg2);
extern int ukl_get_thread_area(struct user_desc  *u_info);
extern int ukl_set_thread_area(struct user_desc  *u_info);
extern unsigned long ukl_mmap(unsigned long addr, unsigned long len, unsigned long prot, unsigned long flags, unsigned long fd, unsigned long off);
extern int ukl_set_tid_address(int * tidptr);
extern int ukl_set_robust_list(struct robust_list_head * head, size_t len);
extern int ukl_rt_sigprocmask(int how, sigset_t * nset,  sigset_t * oset, size_t sigsetsize);
extern int ukl_rt_sigaction(int sig, const struct sigaction * act, struct sigaction * oact, size_t sigsetsize);
extern int ukl_prlimit64(pid_t pid, unsigned int resource, const struct rlimit64 * new_rlim, struct rlimit64 * old_rlim);
extern unsigned long ukl_brk(unsigned long brk);
extern int ukl_fstat(unsigned int fd, struct stat  * statbuf);
extern int ukl_mprotect(unsigned long start, size_t len, unsigned long prot);
extern int ukl_munmap(unsigned long addr, size_t len);
extern void ukl_exit(int error_code);
extern long ukl_futex(unsigned int  * uaddr, int op, unsigned int  val, struct __kernel_timespec * utime, unsigned int  * uaddr2, unsigned int  val3);
extern int ukl_setrlimit (unsigned int  resource, const struct rlimit* rlim);
extern extern u64 ukl_kvm_clock_read(void);
extern int ukl_clock_gettime(const clockid_t which_clock, struct __kernel_timespec * tp);
extern int ukl_gettimeofday(struct timeval* tv, struct timezone* tz);
extern int ukl_epoll_create1(int flags);
extern int ukl_epoll_create(int size);
extern int ukl_pipe2(int* fildes, int flags);
extern time_t ukl_time (time_t *t);
extern int ukl_fcntl(unsigned int fd, unsigned int cmd, unsigned long arg);
extern int ukl_epoll_ctl(int epfd, int op, int fd, struct epoll_event* event);
extern int ukl_epoll_wait(int epfd, struct epoll_event * events, int maxevents, int timeout);
extern int ukl_epoll_pwait(int epfd, struct epoll_event* events, int maxevents, int timeout, const sigset_t * sigmask, size_t sigsetsize);
extern int ukl_nanosleep(struct __kernel_timespec *rqtp, struct __kernel_timespec *rmtp);
extern int ukl_mlock(long start, size_t len);
extern int ukl_mlock2(long start, size_t len, int flags);
extern int ukl_tgkill(pid_t tgid, pid_t pid, int sig);
extern pid_t ukl_getpid(void);
extern pid_t ukl_getppid(void);
extern uid_t ukl_getuid(void);
extern uid_t ukl_geteuid(void);
extern pid_t ukl_gettid(void);
extern gid_t ukl_getgid(void);
extern gid_t ukl_getegid(void);
extern int ukl_sendmmsg(int fd, struct mmsghdr *mmsg, unsigned int vlen, unsigned int flags);
extern long ukl_mknod(const char * filename, umode_t mode, unsigned int dev);
extern int ukl_mount(char * dev_name, char * dir_name, char * type, unsigned long flags, void * data);
extern int ukl_chroot(const char * filename);
extern int ukl_chdir(const char * filename);
extern long ukl_mkdir(const char *pathname, umode_t mode);
extern void ukl_sync(void);
extern int ukl_select(int n, fd_set  * inp, fd_set  * outp, fd_set  * exp, struct __kernel_old_timeval  * tvp);
extern int ukl_poll(struct pollfd * ufds, unsigned int nfds, int timeout_msecs);
extern int ukl_sysinfo(struct sysinfo * info);
extern int ukl_renameat2(int olddfd, const char *oldname, int newdfd, const char *newname, unsigned int flags);
extern int ukl_renameat(int olddfd, const char __user *oldname, int newdfd, const char __user *newname);
extern int ukl_rename(const char *oldname, const char *newname);
extern int ukl_getrusage(int who, struct rusage * ru);
extern off_t ukl_lseek(unsigned int fd, off_t offset, unsigned int whence);
extern int ukl_getpeername(int fd, struct sockaddr *usockaddr, int *usockaddr_len);
extern int ukl_kill(pid_t pid, int sig);
extern int ukl_rt_sigsuspend(sigset_t * unewset, size_t sigsetsize);
extern ssize_t ukl_getrandom(char * buf, size_t count, unsigned int flags);
extern int ukl_settimeofday(struct __kernel_old_timeval * tv, struct timezone * tz);
extern int ukl_getitimer(int which, struct itimerval * value);
extern long ukl_sendmsg(int fd, struct user_msghdr* msg, unsigned int flags);
